sonar.projectKey=emillybudri_integracao-e-entrega-continua
sonar.organization=emillybudri
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=.venv/**,venv/**,**/node_modules/**
sonar.python.version=3.12
