FROM wordpress:latest

# Copia o tema customizado e os mu-plugins para a imagem do WordPress
COPY ./theme /var/www/html/wp-content/themes/portal-cicd
COPY ./mu-plugins /var/www/html/wp-content/mu-plugins
