# O QUE É YAML? Formato de texto legível por humanos estruturado por indentação (use sempre espaços, nunca TAB).

name: Estudo - Estrutura Padrão do Workflow (Resumo Prova) # Nome visível do workflow na aba 'Actions' do GitHub
on:                                                       # Define os eventos/gatilhos que iniciam esta automação
  push:                                                   # Gatilho: executa quando novos commits são enviados ao repositório
    branches: [main, dev]                                 # Filtro: dispara apenas se o push ocorrer nas branches 'main' ou 'dev' (é um array com as branches)

jobs:                                                     # Bloco que agrupa todas as tarefas a serem executadas
  teste:                                                  # ID/nome identificador deste job específico
    runs-on: ubuntu-latest                                # Máquina virtual (Runner) onde o job roda (Ubuntu Linux mais recente)

    steps:                                                # Lista sequencial de passos a executar (aceita 'uses' ou 'run')
      - name: Baixar Código                               # '-' indica um novo item da lista; 'name:' rotula o passo nos logs
        uses: actions/checkout@v4                         # Executa action pronta para clonar o repositório na VM (@v4)

      - name: Configurar linguagem                        # Nome descritivo da etapa de configuração do interpretador
        uses: actions/setup-python@v4                     # Action oficial para instalar e disponibilizar o Python no PATH
        with:                                             # Bloco de parâmetros extras para a action acima
          python-version: "3.12"                          # Versão específica do Python a ser configurada (formato chave/valor)

      - name: Instalar dependencias                       # Nome descritivo do passo de instalação de pacotes
        run: pip install pytest                           # Executa comando de terminal no shell da VM (instala o Pytest via pip)

      - name: Executar soma                               # Nome da etapa de execução dos testes automatizados
        run: pytest test_soma.py                          # Roda o pytest especificamente no arquivo de testes indicado
