name: Atividade 01 - Primeira Pipeline de CI com Python (19/08/2026)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  teste:
    name: Testes Python (${{ matrix.os }} - Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04]
        python-version: ['3.10', '3.11']
    
    steps:
    - name: Baixar Código do Repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'

    - name: Instalar dependências
      run: pip install -r ativ-01/requirements.txt

    - name: Executar testes
      working-directory: ativ-01
      run: pytest

  deploy:
    name: Deploy
    needs: teste
    runs-on: ubuntu-latest
    steps:
      - name: Executar Deploy
        run: echo "Deploy Realizado"
