name: Atividade 05 - Pipeline Matrix com Python (02/09/2026)

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'ativ-05/**'
      - '.github/workflows/ativ-05-pipeline-matrix-py.yml'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'ativ-05/**'
      - '.github/workflows/ativ-05-pipeline-matrix-py.yml'

jobs:
  qualidade:
    name: Testes (${{ matrix.os }} - Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-23.04, ubuntu-24.04]
        python-version: ['3.10', '3.11']

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Instalar dependências
        run: pip install pytest

      - name: Executar testes
        working-directory: ativ-05
        run: pytest