name: Atividade 01 - Primeira Pipeline de CI com Python (19/08/2026)

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'test_exemplo.py'
      - '*.py'
      - '.github/workflows/ativ-01-primeira-pipeline-py.yml'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'test_exemplo.py'
      - '*.py'
      - '.github/workflows/ativ-01-primeira-pipeline-py.yml'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  teste:
    name: Testes Python
    runs-on: ubuntu-latest
    
    steps:
    - name: Baixar Código do Repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar dependências
      run: pip install pytest

    - name: Executar testes
      run: pytest

  deploy:
    name: Deploy
    needs: teste
    runs-on: ubuntu-latest
    steps:
      - name: Executar Deploy
        run: echo "Deploy Realizado"
